# Generated by Django 5.2.6 on 2025-09-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("source", models.CharField(max_length=100)),
                ("target", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=100)),
                ("lag", models.IntegerField(blank=True, default=0)),
            ],
            options={
                "db_table": "dashboard_link",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("text", models.CharField(blank=True, max_length=100)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("duration", models.IntegerField()),
                ("progress", models.FloatField()),
                ("parent", models.CharField(max_length=100)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "dashboard_task",
            },
        ),
    ]
