# Generated by Django 5.2.6 on 2025-09-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="color",
            field=models.CharField(
                default="#4CAF50", help_text="Hex color code for the task", max_length=7
            ),
        ),
    ]
