# Generated by Django 5.2.6 on 2025-10-31 13:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_task_color"),
        ("yats", "0028_alter_boards_id_alter_docs_id_alter_docs_files_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="external_id",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="task",
            name="readonly",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="source",
            field=models.CharField(default="ticket", max_length=50),
        ),
        migrations.CreateModel(
            name="Runfolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "runfolder_name",
                    models.CharField(
                        help_text="Unique identifier for the runfolder",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "runfolder_path",
                    models.CharField(
                        help_text="Full path to the runfolder directory",
                        max_length=500,
                        unique=True,
                    ),
                ),
                (
                    "instrument_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "flowcell_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("run_date", models.DateField(blank=True, null=True)),
                ("run_start_time", models.DateTimeField(blank=True, null=True)),
                ("run_end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initializing", "Initializing"),
                            ("sequencing", "Sequencing"),
                            ("finished", "Finished"),
                            ("copying", "Copying"),
                            ("completed", "Completed"),
                        ],
                        default="initializing",
                        max_length=20,
                    ),
                ),
                (
                    "completion_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("completion_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated sequencing ticket",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runfolders",
                        to="yats.tickets",
                    ),
                ),
            ],
            options={
                "verbose_name": "Runfolder",
                "verbose_name_plural": "Runfolders",
                "ordering": ["-updated_at"],
            },
        ),
    ]
