# Generated by Django 5.2.6 on 2025-10-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_task_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="external_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="External identifier (e.g., MinKNOW run ID)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="readonly",
            field=models.BooleanField(
                default=False,
                help_text="If true, this task cannot be edited or deleted",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="source",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Source of the task (e.g., "minknow", "manual")',
                max_length=50,
            ),
        ),
    ]
